<?php

namespace AppBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
  public function getMsgById($id)
  {
     
     $qb = $this
       ->createQueryBuilder('m')
       ->leftJoin('m.reponses', 'rep')
       ->addSelect('rep')
       ->where('m.id = ?1')
       ->setParameter(1, $id)
     ;
   
     return $qb
       ->getQuery()
       ->getResult()
     ;
  }
}
